export const data = [
    {
        id: "1",
        image: "/m-s.webp",
        title: "Самбо",
        loc: "Мытищи",
        location: "Новомытищинский просп., 76, Мытищи",
        price: "4500",
        shed: "Понедельник",
        shedTime: "19:00",
        shed2: "Среда",
        shedTime2: "19:00",
        shed3: "Воскресенье",
        shedTime3: "17:00",
        ageLimit: "от 4 до 13 лет",
        duration: "60 минут",
    },
    {
        id: "2",
        image: "/sm2.webp",
        title: "Самбо",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Вторник",
        shedTime: "19:00",
        shed2: "Четверг",
        shedTime2: "19:00",
        shed3: "Воскресенье",
        shedTime3: "14:00",
        ageLimit: "от 7 до 14 лет",
        duration: "90 минут",
    },
    {
        id: "3",
        image: "/jd.webp",
        title: "Дзюдо",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Понедельник",
        shedTime: "17:30",
        shed2: "Среда",
        shedTime2: "17:30",
        shed3: "Пятница",
        shedTime3: "17:30",
        ageLimit: "от 4 до 7 лет",
        duration: "60 минут",
    },
    {
        id: "4",
        image: "/jd2.webp",
        title: "Дзюдо",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Понедельник",
        shedTime: "18:30",
        shed2: "Среда",
        shedTime2: "18:30",
        shed3: "Пятница",
        shedTime3: "18:30",
        ageLimit: "от 7 до 14 лет",
        duration: "90 минут",
    },
    {
        id: "5",
        image: "/tk.webp",
        title: "Тхэквондо",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Вторник",
        shedTime: "17:00",
        shed2: "Четверг",
        shedTime2: "17:00",
        shed3: "Воскресенье",
        shedTime3: "16:00",
        ageLimit: "от 7 до 16 лет",
        duration: "60 минут",
    },
    {
        id: "6",
        image: "/tk2.webp",
        title: "Тхэквондо",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Вторник",
        shedTime: "18:00",
        shed2: "Четверг",
        shedTime2: "18:00",
        shed3: "Воскресенье",
        shedTime3: "16:00",
        ageLimit: "от 3 до 7 лет",
        duration: "60 минут",
    },
    {
        id: "7",
        image: "/ch.webp",
        title: "Шахматы",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Понедельник",
        shedTime: "17:30",
        shed2: "Среда",
        shedTime2: "17:30",
        shed3: null,
        shedTime3: null,
        ageLimit: "от 7 до 14 лет",
        duration: "60 минут",
    },
    {
        id: "8",
        image: "/ch2.webp",
        title: "Шахматы",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Понедельник",
        shedTime: "18:30",
        shed2: "Среда",
        shedTime2: "18:30",
        shed3: null,
        shedTime3: null,
        ageLimit: "от 5 до 7 лет",
        duration: "60 минут",
    },
    {
        id: "9",
        image: "/ch3.webp",
        title: "Брейк данс",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Среда",
        shedTime: "20:00",
        shed2: "Пятница",
        shedTime2: "20:00",
        shed3: null,
        shedTime3: null,
        ageLimit: "от 5 до 16 лет",
        duration: "60 минут",
    },
    {
        id: "10",
        image: "/m-s.webp",
        title: "Подгатовка к школе",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "3500",
        shed: "Вторник",
        shedTime: "15:45",
        shed2: "Пятница",
        shedTime2: "15:45",
        shed3: null,
        shedTime3: null,
        ageLimit: "от 5 до 16 лет",
        duration: "60 минут",
    },
    {
        id: "11",
        image: "/ch3.webp",
        title: "Шахматы",
        loc: "пос. Зеленоградский",
        location: "п. Зеленоградский, ул. Шоссейная 2В",
        price: "2500",
        shed: "Вторник",
        shedTime: "14:00",
        shed2: "Четверг",
        shedTime2: "14:00",
        shed3: null,
        shedTime3: null,
        ageLimit: "от 7 до 12 лет",
        duration: "60 минут",
    },
    {
        id: "12",
        image: "/ch3.webp",
        title: "Шахматы",
        loc: "пос. Лесной",
        location: "п. Лесной, ул. Титова 11, Школа",
        price: "2500",
        shed: "Вторник",
        shedTime: "14:30",
        shed2: "Четверг",
        shedTime2: "14:30",
        shed3: null,
        shedTime3: null,
        ageLimit: "от 7 до 12 лет",
        duration: "60 минут",
    },
];
